const game = [
    {
        id:1,
        name:'Flappy bird',
        url:'/flappy',
        logo:'https://is4-ssl.mzstatic.com/image/thumb/Purple71/v4/d5/b0/76/d5b0769d-85a4-a43f-fa7d-80f6fcb2fda7/source/512x512bb.jpg',
        players:[
            {
                id:1,
                name:'John',
                bestScore:100,
                profile:"https://s3-ap-northeast-1.amazonaws.com/peatix-files/user/5562732/240administrator-male.png"
            },
            {
                id:2,
                name:'Doe',
                bestScore:200,
                profile:"https://s3-ap-northeast-1.amazonaws.com/peatix-files/user/5562732/240administrator-male.png"
            },
            {
                id:3,
                name:'Williams',
                bestScore:300,
                profile:"https://s3-ap-northeast-1.amazonaws.com/peatix-files/user/5562732/240administrator-male.png"
            },
        ]
    },
    {
        id:2,
        name:'Breakout',
        url:'/brick',
        logo:'https://firebasestorage.googleapis.com/v0/b/fir-imagestore-5410f.appspot.com/o/logos%2Fbrakout.jpeg?alt=media&token=58411bbd-5094-404c-8ecb-54925b8dffea',
        players:[
            {
                id:1,
                name:'John',
                bestScore:300,
                profile:"https://s3-ap-northeast-1.amazonaws.com/peatix-files/user/5562732/240administrator-male.png"
            },
            {
                id:2,
                name:'Doe',
                bestScore:200,
                profile:"https://s3-ap-northeast-1.amazonaws.com/peatix-files/user/5562732/240administrator-male.png"
            },
            {
                id:3,
                name:'Williams',
                bestScore:400,
                profile:"https://s3-ap-northeast-1.amazonaws.com/peatix-files/user/5562732/240administrator-male.png",
            },
        ]
    },
    {
        id:3,
        name:'Snake',
        url:'/snake',
        logo:'https://firebasestorage.googleapis.com/v0/b/fir-imagestore-5410f.appspot.com/o/logos%2Fsnake.jpeg?alt=media&token=f233d34f-d30c-43ee-9d08-951c4b1e5a31',
        players:[
            {
                id:1,
                name:'Johns',
                bestScore:100,
                profile:"https://s3-ap-northeast-1.amazonaws.com/peatix-files/user/5562732/240administrator-male.png"
            },
            {
                id:2,
                name:'Doed',
                bestScore:200,
                profile:"https://s3-ap-northeast-1.amazonaws.com/peatix-files/user/5562732/240administrator-male.png"
            },
            {
                id:3,
                name:'smith',
                bestScore:300,
                profile:"https://s3-ap-northeast-1.amazonaws.com/peatix-files/user/5562732/240administrator-male.png"
            },
        ]
    },
    {
        id:4,
        name:'TICTACTOE',
        url:'/snake',
        logo:'https://firebasestorage.googleapis.com/v0/b/fir-imagestore-5410f.appspot.com/o/logos%2Ftictactoe.jpeg?alt=media&token=12c08de1-194e-45dd-8f7d-1b137f4ed694',
        players:[
            {
                id:1,
                name:'Johns',
                bestScore:100,
                profile:"https://s3-ap-northeast-1.amazonaws.com/peatix-files/user/5562732/240administrator-male.png"
            },
            {
                id:2,
                name:'Doed',
                bestScore:200,
                profile:"https://s3-ap-northeast-1.amazonaws.com/peatix-files/user/5562732/240administrator-male.png"
            },
            {
                id:3,
                name:'smith',
                bestScore:300,
                profile:"https://s3-ap-northeast-1.amazonaws.com/peatix-files/user/5562732/240administrator-male.png"
            },
        ]
    },
    {
        id:5,
        name:'rock paper scissor',
        url:'/snake',
        logo:'https://firebasestorage.googleapis.com/v0/b/fir-imagestore-5410f.appspot.com/o/logos%2Frockpapsicss.jpeg?alt=media&token=567f0549-f9eb-4786-9dab-72a139ed7b11',
        players:[
            {
                id:1,
                name:'Johns',
                bestScore:100,
                profile:"https://s3-ap-northeast-1.amazonaws.com/peatix-files/user/5562732/240administrator-male.png"
            },
            {
                id:2,
                name:'Doed',
                bestScore:200,
                profile:"https://s3-ap-northeast-1.amazonaws.com/peatix-files/user/5562732/240administrator-male.png"
            },
            {
                id:3,
                name:'smith',
                bestScore:300,
                profile:"https://s3-ap-northeast-1.amazonaws.com/peatix-files/user/5562732/240administrator-male.png"
            },
        ]
    },
]

export default game